import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Download, Folder, FolderInput, Grid2X2, HardDrive, History, Image as ImageIcon, KeyRound, List, LogOut, Pencil, RotateCcw, Search, Share2, Shield, Trash2, UploadCloud, X} from 'lucide-react';
import './style.css';
import './trash.css';

const API = import.meta.env.VITE_API_URL || '/api';
const csrf = () => document.cookie.split('; ').find(v => v.startsWith('XSRF-TOKEN='))?.split('=').slice(1).join('=') || '';
async function api(path, options = {}) {
  const headers = new Headers(options.headers || {});
  if (['POST', 'PUT', 'PATCH', 'DELETE'].includes((options.method || 'GET').toUpperCase())) {
    const token = csrf(); if (token) headers.set('X-CSRF-Token', decodeURIComponent(token));
  }
  const response = await fetch(API + path, {credentials: 'include', ...options, headers});
  if (!response.ok) { const body = await response.json().catch(() => ({})); const details = body.error || body; const error = new Error(details.message || `İstek başarısız (${response.status})`); error.status = response.status; error.code = details.code; throw error; }
  return response.status === 204 ? null : response.json();
}
const formatBytes = n => n < 1024 ? `${n} B` : n < 1048576 ? `${(n / 1024).toFixed(1)} KB` : n < 1073741824 ? `${(n / 1048576).toFixed(1)} MB` : `${(n / 1073741824).toFixed(2)} GB`;

export function App() {
  const [files, setFiles] = useState([]), [folders, setFolders] = useState([]), [folder, setFolder] = useState(null), [folderPath, setFolderPath] = useState([]);
  const [usage, setUsage] = useState({used_bytes: 0, quota_bytes: 1}), [signedIn, setSignedIn] = useState(true);
  const [error, setError] = useState(''), [query, setQuery] = useState(''), [sort, setSort] = useState('created_at'), [view, setView] = useState('grid');
  const [upload, setUpload] = useState(null), [dragging, setDragging] = useState(false), [shareFile, setShareFile] = useState(null), [moveFile, setMoveFile] = useState(null), [versionsFile, setVersionsFile] = useState(null);
  const [section, setSection] = useState('files');
  const [selected, setSelected] = useState([]), [bulkMoveFiles, setBulkMoveFiles] = useState([]);
  const [passwordDialog, setPasswordDialog] = useState(false), [sessionsDialog, setSessionsDialog] = useState(false), [totpDialog, setTotpDialog] = useState(false), [accountDialog, setAccountDialog] = useState(false), [newFolderDialog, setNewFolderDialog] = useState(false);
  const [emailVerified, setEmailVerified] = useState(true), [verificationMessage, setVerificationMessage] = useState('');
  const [resetToken, setResetToken] = useState(() => new URLSearchParams(window.location.search).get('reset') || '');
  const load = async (currentFolder = folder, currentSection = section) => { try { const storageRequest = api('/v1/storage'); if (currentSection === 'trash') { const [fileData, folderData, storage] = await Promise.all([api('/v1/trash?limit=100'), api('/v1/trash/folders?limit=100'), storageRequest]); setFiles(fileData.files || []); setFolders(folderData.folders || []); setUsage(storage); } else if (currentSection === 'shared') { const result = await api('/v1/shared-with-me'); setFiles((result.items || []).map(item => ({id: item.file_id, name: item.file_name, size_bytes: 0, created_at: item.created_at, shared_by: item.owner_email, permission: item.permission}))); setFolders([]); } else { const suffix = currentFolder ? `&folder_id=${currentFolder.id}` : ''; const parent = currentFolder ? `?parent_id=${currentFolder.id}` : ''; const [fileData, folderData, storage] = await Promise.all([api(`/v1/files?limit=50${suffix}`), api(`/v1/folders${parent}`), storageRequest]); setFiles(fileData.items || fileData.files || fileData); setFolders(folderData.items || folderData.folders || folderData); setUsage(storage); } setSignedIn(true); setError(''); } catch (e) { if (e.status === 401) setSignedIn(false); else setError(e.message); } };
  useEffect(() => { api('/v1/auth/csrf').catch(() => {}); const token = new URLSearchParams(window.location.search).get('verify'); if (token) { api('/v1/auth/email/verify', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({token})}).then(() => { setEmailVerified(true); setVerificationMessage('E-posta adresin doğrulandı.'); window.history.replaceState({}, '', window.location.pathname); }).catch(e => setVerificationMessage(e.message)); } }, []);
  useEffect(() => { load(folder, section); }, [folder, section, sort]);
  useEffect(() => { setSelected([]); }, [folder, section]);
  useEffect(() => { if (section !== 'files') return; if (!query.trim()) { load(folder, section); return; } const timer = setTimeout(() => { api(`/v1/search?q=${encodeURIComponent(query.trim())}&limit=50`).then(result => { setFiles((result.files || []).map(item => ({...item, name: item.name || item.original_name}))); setFolders(result.folders || []); }).catch(e => setError(e.message)); }, 250); return () => clearTimeout(timer); }, [query, section]);
  useEffect(() => { if (signedIn) api('/v1/auth/email/status').then(result => setEmailVerified(result.verified)).catch(() => {}); }, [signedIn]);
  const uploadMultipart = async file => { const digest = await crypto.subtle.digest('SHA-256', await file.arrayBuffer()); const checksum = [...new Uint8Array(digest)].map(value => value.toString(16).padStart(2, '0')).join(''); const key = `cloudlet-upload-${checksum}`; let intentId = ''; try { const saved = JSON.parse(localStorage.getItem(key) || 'null'); const started = saved ? await api(`/v1/uploads/${saved.intent_id}`) : await api('/v1/uploads', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({name: file.name, content_type: file.type || 'application/octet-stream', checksum_sha256: checksum, idempotency_key: crypto.randomUUID(), folder_id: folder?.id || null, size_bytes: file.size})}); intentId = started.intent_id; localStorage.setItem(key, JSON.stringify({intent_id: intentId, name: file.name, size: file.size})); const completed = new Map((started.completed_parts || []).map(part => [part.part_number, part.etag])); const parts = []; for (const part of started.parts) { if (completed.has(part.part_number)) { parts.push({part_number: part.part_number, etag: completed.get(part.part_number)}); setUpload({name: file.name, progress: Math.round(part.part_number / started.parts.length * 100)}); continue; } const begin = (part.part_number - 1) * started.part_size; let response; for (let attempt = 1; attempt <= 3; attempt++) { try { response = await fetch(part.url, {method: 'PUT', body: file.slice(begin, Math.min(begin + started.part_size, file.size))}); if (response.ok) break; } catch (error) { if (attempt === 3) throw error; } if (attempt < 3) await new Promise(resolve => setTimeout(resolve, attempt * 700)); } if (!response?.ok) throw new Error(`Multipart ${part.part_number}. parça yüklenemedi.`); parts.push({part_number: part.part_number, etag: response.headers.get('ETag')?.replaceAll('"', '') || response.headers.get('etag')?.replaceAll('"', '')}); setUpload({name: file.name, progress: Math.round(part.part_number / started.parts.length * 100)}); } await api(`/v1/uploads/${intentId}/complete`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({parts})}); localStorage.removeItem(key); await load(folder); } catch (error) { throw error; } };
  const uploadViaAPI = file => new Promise((resolve, reject) => { const body = new FormData(); body.append('file', file); if (folder) body.append('folder_id', folder.id); const request = new XMLHttpRequest(); request.open('POST', API + '/v1/files'); request.withCredentials = true; const token = csrf(); if (token) request.setRequestHeader('X-CSRF-Token', decodeURIComponent(token)); request.upload.onprogress = e => e.lengthComputable && setUpload({name: file.name, progress: Math.round(e.loaded / e.total * 100)}); request.onload = () => request.status >= 200 && request.status < 300 ? resolve() : reject(new Error('Dosya yüklenemedi. Kota ve dosya türünü kontrol et.')); request.onerror = () => reject(new Error('Yükleme sırasında ağ bağlantısı kesildi.')); request.send(body); });
  const uploadFile = file => { if (!file || upload) return; setUpload({name: file.name, progress: 0}); if (file.size >= 5 * 1024 * 1024) { uploadMultipart(file).catch(() => uploadViaAPI(file)).then(() => load(folder)).catch(e => setError(e.message || 'Dosya yüklenemedi.')).finally(() => setUpload(null)); return; } uploadViaAPI(file).then(() => load(folder)).catch(e => setError(e.message)).finally(() => setUpload(null)); };
  if (resetToken) return <ResetPassword token={resetToken} onDone={() => { setResetToken(''); setSignedIn(false); window.history.replaceState({}, '', window.location.pathname); }}/>;
  if (!signedIn) return <Login onSuccess={() => load(folder)} error={error} setError={setError}/>;
  const createFolder = async name => { const options = {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({name: name.trim(), parent_id: folder?.id || null})}; try { await api('/v1/folders', options); } catch (error) { if (error.status === 403) { await api('/v1/auth/csrf'); await api('/v1/folders', options); } else throw error; } setNewFolderDialog(false); await load(folder); };
  const logout = async () => { try { await api('/v1/auth/logout', {method: 'POST'}); } finally { setSignedIn(false); } };
  const openSection = next => { setFolder(null); setFolderPath([]); setQuery(''); setSort('created_at'); setSection(next); };
  const openFolder = item => { setFolder(item); setFolderPath(current => [...current, item]); };
  const navigatePath = index => { const next = index < 0 ? null : folderPath[index]; setFolder(next); setFolderPath(index < 0 ? [] : folderPath.slice(0, index + 1)); };
  const moveToTrash = async file => { try { await api(`/v1/files/${file.id}`, {method: 'DELETE'}); await load(folder, section); } catch (e) { setError(e.message); } };
  const downloadFile = async (file, shared = false) => { try { const result = await api(`${shared ? '/v1/shared-with-me' : '/v1/files'}/${shared ? file.id + '/download' : file.id + '/download'}`); window.open(result.url, '_blank', 'noopener,noreferrer'); } catch (e) { setError(e.message); } };
  const renameFile = async file => { const name = window.prompt('Yeni dosya adı', file.name); if (!name?.trim() || name.trim() === file.name) return; try { await api(`/v1/files/${file.id}`, {method: 'PATCH', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({name: name.trim()})}); await load(folder, section); } catch (e) { setError(e.message); } };
  const toggleSelected = id => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);
  const bulkTrash = async () => { if (!selected.length || !window.confirm(`${selected.length} dosya çöp kutusuna taşınsın mı?`)) return; try { await api('/v1/files/bulk/trash', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({ids: selected})}); setSelected([]); await load(folder, section); } catch (e) { setError(e.message); } };
  const trashAction = async (kind, item, permanent = false) => { if (permanent && !window.confirm(`“${item.original_name || item.name}” kalıcı olarak silinsin mi? Bu işlem geri alınamaz.`)) return; const base = kind === 'folder' ? `/v1/trash/folders/${item.id}` : `/v1/trash/${item.id}`; try { await api(permanent ? base : `${base}/restore`, {method: permanent ? 'DELETE' : 'POST'}); await load(null, 'trash'); } catch (e) { setError(e.message); } };
  const resendVerification = async () => { try { await api('/v1/auth/email/resend', {method: 'POST'}); setVerificationMessage('Yeni doğrulama e-postası gönderildi.'); } catch (e) { setError(e.message); } };
  const visible = files.filter(file => !query || file.name.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name, 'tr') : sort === 'size' ? (b.size_bytes || 0) - (a.size_bytes || 0) : new Date(b.created_at) - new Date(a.created_at));
  const usedPercent = Math.min(100, usage.used_bytes / Math.max(usage.quota_bytes, 1) * 100);
  return <div className="shell" onDragEnter={e => { e.preventDefault(); setDragging(true); }}>
    <aside><div className="brand"><span className="mark">C</span><span>cloudlet</span></div><div className="eyebrow">KİŞİSEL ALAN</div><nav><button className={section === 'files' ? 'active' : ''} onClick={() => openSection('files')}><HardDrive size={17}/>Dosyalar</button><button className={section === 'shared' ? 'active' : ''} onClick={() => openSection('shared')}><Share2 size={17}/>Paylaşılanlar</button><button className={section === 'trash' ? 'active' : ''} onClick={() => openSection('trash')}><Trash2 size={17}/>Çöp kutusu</button></nav><div className="quota"><div className="quota-head"><span>Depolama</span><b>{formatBytes(usage.used_bytes)}</b></div><div className="bar"><i style={{width: `${usedPercent}%`}}/></div><small>{formatBytes(usage.quota_bytes)} toplam</small></div><button className="logout" onClick={() => setPasswordDialog(true)}><KeyRound size={15}/>Parola değiştir</button><button className="logout" onClick={() => setTotpDialog(true)}><Shield size={15}/>2FA güvenliği</button><button className="logout" onClick={() => setSessionsDialog(true)}><Shield size={15}/>Oturumlar</button><button className="logout" onClick={() => setAccountDialog(true)}><Trash2 size={15}/>Hesabı kapat</button><button className="logout" onClick={logout}><LogOut size={15}/>Çıkış yap</button></aside>
    <main><header><div><div className="eyebrow">{section === 'trash' ? '30 GÜN SAKLANIR' : 'DOSYA ALANI / BUGÜN'}</div><h1>{section === 'trash' ? <>Silinen <em>öğeler.</em></> : <>Dosyaların, <em>senin</em> düzenin.</>}</h1></div>{section === 'files' && <div className="header-actions"><button className="secondary" onClick={() => setNewFolderDialog(true)}><Folder size={16}/>Yeni klasör</button><label className="upload"><UploadCloud size={17}/>Dosya yükle<input type="file" onChange={e => { uploadFile(e.target.files?.[0]); e.target.value = ''; }}/></label></div>}</header>
      {!emailVerified && <div className="verify-banner"><span><strong>E-posta adresini doğrula</strong> Paylaşım bağlantısı oluşturmak için gelen kutundaki bağlantıyı aç.</span><button onClick={resendVerification}>Tekrar gönder</button></div>}
      {verificationMessage && <div className="success">{verificationMessage}<button onClick={() => setVerificationMessage('')}><X size={14}/></button></div>}
      {upload && <div className="upload-progress"><span>{upload.name}</span><div><i style={{width: `${upload.progress}%`}}/></div><b>%{upload.progress}</b></div>}
      <section className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Bu klasörde ara…"/></div><select className="sort-select" value={sort} onChange={e => setSort(e.target.value)}><option value="created_at">En yeni</option><option value="name">Ada göre</option><option value="size">Boyuta göre</option></select><div className="view-toggle"><button className={view === 'grid' ? 'selected' : ''} onClick={() => setView('grid')} aria-label="Izgara"><Grid2X2 size={16}/></button><button className={view === 'list' ? 'selected' : ''} onClick={() => setView('list')} aria-label="Liste"><List size={16}/></button></div></section>
      {selected.length > 0 && section === 'files' && <div className="bulk-toolbar"><strong>{selected.length} dosya seçildi</strong><button onClick={() => setBulkMoveFiles(files.filter(file => selected.includes(file.id)))}><FolderInput size={15}/>Taşı</button><button className="bulk-danger" onClick={bulkTrash}><Trash2 size={15}/>Çöpe taşı</button><button className="bulk-clear" onClick={() => setSelected([])}>Seçimi kaldır</button></div>}
      {error && <div className="error">{error}<button onClick={() => setError('')}><X size={14}/></button></div>}
      <div className="section-title"><h2>{section === 'trash' ? 'Çöp kutusu' : section === 'shared' ? 'Paylaşılanlar' : <><button className="back" onClick={() => navigatePath(-1)}>Tüm dosyalar</button>{folderPath.map((item, index) => <React.Fragment key={item.id}> <span className="breadcrumb-sep">/</span> <button className="back" onClick={() => navigatePath(index)}>{item.name}</button></React.Fragment>)}</>}</h2><span>{visible.length + folders.length} öğe</span></div>
      <section className={view === 'grid' ? 'file-grid' : 'file-list'}>{folders.map(item => section === 'trash' ? <article className="folder-card" key={item.id}><span className="folder-icon"><Folder size={24}/></span><span><strong>{item.name}</strong><small>Silinmiş klasör</small></span><TrashActions onRestore={() => trashAction('folder', item)} onDelete={() => trashAction('folder', item, true)}/></article> : <button className="folder-card" key={item.id} onClick={() => openFolder(item)}><span className="folder-icon"><Folder size={24}/></span><span><strong>{item.name}</strong><small>Klasör</small></span></button>)}{visible.map(file => <FileCard key={file.id} file={file} selected={selected.includes(file.id)} onSelect={() => toggleSelected(file.id)} shared={section === 'shared'} trashed={section === 'trash'} onShare={() => setShareFile(file)} onVersions={() => setVersionsFile(file)} onMove={() => setMoveFile(file)} onRename={() => renameFile(file)} onDownload={() => downloadFile(file, section === 'shared')} onTrash={() => moveToTrash(file)} onRestore={() => trashAction('file', file)} onDelete={() => trashAction('file', file, true)}/>)}</section>
      {!visible.length && !folders.length && <div className="empty"><Trash2 size={34}/><h3>{section === 'trash' ? 'Çöp kutusu boş' : 'Bu klasör boş'}</h3><p>{section === 'trash' ? 'Sildiğin dosya ve klasörler burada görünür.' : 'Dosya yükle veya yeni bir klasör oluştur.'}</p></div>}
    </main>
    {dragging && <div className="drop-zone" onDragOver={e => e.preventDefault()} onDragLeave={() => setDragging(false)} onDrop={e => { e.preventDefault(); setDragging(false); uploadFile(e.dataTransfer.files?.[0]); }}><UploadCloud size={42}/><strong>Dosyayı buraya bırak</strong></div>}
    {shareFile && <ShareDialog file={shareFile} onClose={() => setShareFile(null)}/>} 
    {moveFile && <MoveDialog file={moveFile} onClose={() => setMoveFile(null)} onMoved={() => { setMoveFile(null); load(folder, section); }}/>} 
    {bulkMoveFiles.length > 0 && <MoveDialog files={bulkMoveFiles} onClose={() => setBulkMoveFiles([])} onMoved={() => { setBulkMoveFiles([]); setSelected([]); load(folder, section); }}/>} 
    {passwordDialog && <ChangePasswordDialog onClose={() => setPasswordDialog(false)} onDone={logout}/>} 
    {versionsFile && <VersionsDialog file={versionsFile} onClose={() => setVersionsFile(null)} onRestored={() => { setVersionsFile(null); load(folder, section); }}/>} 
    {sessionsDialog && <SessionsDialog onClose={() => setSessionsDialog(false)} onLogout={logout}/>} 
    {totpDialog && <TOTPDialog onClose={() => setTotpDialog(false)}/>} 
    {accountDialog && <CloseAccountDialog onClose={() => setAccountDialog(false)} onDone={() => setSignedIn(false)}/>} 
    {newFolderDialog && <NewFolderDialog onClose={() => setNewFolderDialog(false)} onCreate={createFolder}/>} 
  </div>;
}

export function Login({onSuccess, error, setError}) {
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [totpCode, setTotpCode] = useState(''), [totpRequired, setTotpRequired] = useState(false), [busy, setBusy] = useState(false);
  const [mode, setMode] = useState('login');
  const [notice, setNotice] = useState('');
  const submit = async e => { e.preventDefault(); setBusy(true); setError(''); setNotice(''); try { if (mode === 'forgot') { await api('/v1/auth/password/forgot', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({email})}); setNotice('Bu adres kayıtlıysa parola yenileme bağlantısı gönderildi.'); } else { await api(`/v1/auth/${mode === 'login' ? 'login' : 'register'}`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({email, password, ...(mode === 'login' && totpCode ? {totp_code: totpCode} : {})})}); await onSuccess(); } } catch (requestError) { if (requestError.code === 'totp_required') setTotpRequired(true); setError(mode === 'login' ? requestError.code === 'invalid_totp' ? 'Doğrulama kodu geçersiz.' : requestError.code === 'totp_required' ? 'Authenticator uygulamandaki 6 haneli kodu gir.' : 'E-posta veya parola hatalı.' : requestError.message); } finally { setBusy(false); } };
  const switchMode = () => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); };
  const forgot = mode === 'forgot';
  return <div className="auth-shell"><div className="auth-card"><div className="brand"><span className="mark">C</span><span>cloudlet</span></div><div className="eyebrow">{forgot ? 'HESABINI KURTAR' : mode === 'login' ? 'KİŞİSEL ALANINA DÖN' : '5 GB ÜCRETSİZ ALAN'}</div><h1>{forgot ? <>Parolanı<br/><em>yenile.</em></> : mode === 'login' ? <>Dosyaların seni<br/><em>bekliyor.</em></> : <>Alanını şimdi<br/><em>oluştur.</em></>}</h1><p>{forgot ? 'E-posta adresine 30 dakika geçerli güvenli bir bağlantı göndereceğiz.' : mode === 'login' ? 'Güvenli alanına giriş yap ve kaldığın yerden devam et.' : 'Dosyalarını private object storage üzerinde güvenle saklamaya başla.'}</p><form onSubmit={submit}><label>E-posta<input type="email" autoComplete="email" required value={email} onChange={e => setEmail(e.target.value)}/></label>{!forgot && <label>Parola<input type="password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} minLength={12} required value={password} onChange={e => setPassword(e.target.value)}/></label>}{totpRequired && mode === 'login' && <label>Authenticator kodu<input inputMode="numeric" pattern="[0-9]{6}" maxLength="6" autoComplete="one-time-code" required value={totpCode} onChange={e => setTotpCode(e.target.value.replace(/\D/g, ''))}/></label>}{mode === 'register' && <small className="password-hint">En az 12 karakter kullan.</small>}{notice && <div className="success">{notice}</div>}{error && <div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy ? 'Lütfen bekle…' : forgot ? 'Bağlantı gönder' : mode === 'login' ? 'Giriş yap' : 'Hesap oluştur'}</button></form>{mode === 'login' && <button className="auth-switch" type="button" onClick={() => { setMode('forgot'); setError(''); }}>Parolamı unuttum</button>}<button className="auth-switch" type="button" onClick={forgot ? () => setMode('login') : switchMode}>{forgot ? 'Giriş ekranına dön' : mode === 'login' ? 'Hesabın yok mu? Alanını oluştur' : 'Zaten hesabın var mı? Giriş yap'}</button></div></div>;
}

function ResetPassword({token, onDone}) {
  const [password, setPassword] = useState(''), [confirmation, setConfirmation] = useState(''), [error, setError] = useState(''), [done, setDone] = useState(false), [busy, setBusy] = useState(false);
  const submit = async e => { e.preventDefault(); if (password !== confirmation) { setError('Parolalar eşleşmiyor.'); return; } setBusy(true); setError(''); try { await api('/v1/auth/password/reset', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({token, password})}); setDone(true); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } };
  return <div className="auth-shell"><div className="auth-card"><div className="brand"><span className="mark">C</span><span>cloudlet</span></div><div className="eyebrow">GÜVENLİ PAROLA YENİLEME</div><h1>{done ? <>Parolan<br/><em>yenilendi.</em></> : <>Yeni parolanı<br/><em>belirle.</em></>}</h1>{done ? <><p>Tüm açık oturumların kapatıldı. Yeni parolanla tekrar giriş yapabilirsin.</p><button className="primary full" onClick={onDone}>Giriş yap</button></> : <form onSubmit={submit}><label>Yeni parola<input type="password" autoComplete="new-password" minLength={12} required value={password} onChange={e => setPassword(e.target.value)}/></label><label>Yeni parola tekrar<input type="password" autoComplete="new-password" minLength={12} required value={confirmation} onChange={e => setConfirmation(e.target.value)}/></label><small className="password-hint">En az 12 karakter kullan.</small>{error && <div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy ? 'Yenileniyor…' : 'Parolayı yenile'}</button></form>}</div></div>;
}

function ChangePasswordDialog({onClose, onDone}) {
  const [currentPassword, setCurrentPassword] = useState(''), [password, setPassword] = useState(''), [confirmation, setConfirmation] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const submit = async e => { e.preventDefault(); if (password !== confirmation) { setError('Yeni parolalar eşleşmiyor.'); return; } setBusy(true); setError(''); try { await api('/v1/auth/password/change', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({current_password: currentPassword, password})}); onDone(); } catch (requestError) { setError(requestError.message); setBusy(false); } };
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="password-title"><button className="modal-close" onClick={onClose}><X size={18}/></button><div className="eyebrow">HESAP GÜVENLİĞİ</div><h2 id="password-title">Parolanı değiştir</h2><form onSubmit={submit}><label>Mevcut parola<input type="password" autoComplete="current-password" required value={currentPassword} onChange={e => setCurrentPassword(e.target.value)}/></label><label>Yeni parola<input type="password" autoComplete="new-password" minLength={12} required value={password} onChange={e => setPassword(e.target.value)}/></label><label>Yeni parola tekrar<input type="password" autoComplete="new-password" minLength={12} required value={confirmation} onChange={e => setConfirmation(e.target.value)}/></label><small className="password-hint">En az 12 karakter kullan. Değişiklikten sonra tüm oturumlar kapatılır.</small>{error && <div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy ? 'Değiştiriliyor…' : 'Parolayı değiştir'}</button></form></section></div>;
}

export function CloseAccountDialog({onClose, onDone}) {
  const [password, setPassword] = useState(''), [confirmation, setConfirmation] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const submit = async e => { e.preventDefault(); if (confirmation !== 'HESABIMI SİL') { setError('Onay metnini aynen yazmalısın.'); return; } setBusy(true); setError(''); try { await api('/v1/auth/account', {method: 'DELETE', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({password})}); onDone(); } catch (requestError) { setError(requestError.message); setBusy(false); } };
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="account-close-title"><button className="modal-close" onClick={onClose}><X size={18}/></button><div className="eyebrow">GERİ ALINAMAZ İŞLEM</div><h2 id="account-close-title">Hesabını kapat</h2><p>Tüm dosyaların, sürümlerin, paylaşımların ve oturumların kalıcı olarak silinir.</p><form onSubmit={submit}><label>Mevcut parola<input type="password" autoComplete="current-password" required value={password} onChange={e => setPassword(e.target.value)}/></label><label>Onaylamak için HESABIMI SİL yaz<input required value={confirmation} onChange={e => setConfirmation(e.target.value)}/></label>{error && <div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy ? 'Hesap kapatılıyor…' : 'Hesabı kalıcı olarak kapat'}</button></form></section></div>;
}

function TOTPDialog({onClose}) {
  const [enabled, setEnabled] = useState(false), [setup, setSetup] = useState(null), [code, setCode] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false), [copied, setCopied] = useState(false);
  useEffect(() => { api('/v1/auth/totp').then(result => setEnabled(result.enabled)).catch(e => setError(e.message)); }, []);
  const start = async () => { setBusy(true); setError(''); try { setSetup(await api('/v1/auth/totp/setup', {method: 'POST'})); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const confirm = async e => { e.preventDefault(); setBusy(true); setError(''); try { await api('/v1/auth/totp/enable', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({code})}); setEnabled(true); setSetup(null); setCode(''); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const disable = async e => { e.preventDefault(); setBusy(true); setError(''); try { await api('/v1/auth/totp/disable', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({code})}); setEnabled(false); setCode(''); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const copy = async value => { try { await navigator.clipboard.writeText(value); setCopied(true); setTimeout(() => setCopied(false), 1500); } catch {} };
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="totp-title"><button className="modal-close" onClick={onClose}><X size={18}/></button><div className="eyebrow">HESAP GÜVENLİĞİ</div><h2 id="totp-title">İki faktörlü doğrulama</h2><p>{enabled ? 'Authenticator kodu girişlerde zorunlu.' : 'Authenticator uygulamasıyla hesabına ek güvenlik katmanı ekle.'}</p>{error && <div className="error">{error}</div>}{!enabled && !setup && <button className="primary" onClick={start} disabled={busy}>{busy ? 'Hazırlanıyor…' : '2FA kurulumunu başlat'}</button>}{setup && !enabled && <form onSubmit={confirm}><label>Gizli anahtar<div className="copy-row"><input readOnly value={setup.secret}/><button type="button" className="secondary" onClick={() => copy(setup.secret)}>Kopyala</button></div></label><p>Bu anahtarı authenticator uygulamana ekle veya URI’yi kullan.</p><label>Doğrulama kodu<input inputMode="numeric" pattern="[0-9]{6}" maxLength="6" autoComplete="one-time-code" required value={code} onChange={e => setCode(e.target.value.replace(/\D/g, ''))}/></label><button className="primary" disabled={busy}>{busy ? 'Doğrulanıyor…' : '2FA’yı etkinleştir'}</button>{copied && <small>Kopyalandı.</small>}</form>}{enabled && <form onSubmit={disable}><label>Kapatmak için authenticator kodunu gir<input inputMode="numeric" pattern="[0-9]{6}" maxLength="6" autoComplete="one-time-code" required value={code} onChange={e => setCode(e.target.value.replace(/\D/g, ''))}/></label><button className="secondary" disabled={busy}>2FA’yı kapat</button></form>}</section></div>;
}

function SessionsDialog({onClose, onLogout}) {
  const [sessions, setSessions] = useState([]), [error, setError] = useState('');
  useEffect(() => { api('/v1/auth/sessions').then(result => setSessions(result.sessions || [])).catch(e => setError(e.message)); }, []);
  const revoke = async id => { try { await api(`/v1/auth/sessions/${id}`, {method: 'DELETE'}); setSessions(current => current.filter(item => item.id !== id)); } catch (e) { setError(e.message); } };
  const revokeAll = async () => { try { await api('/v1/auth/logout-all', {method: 'POST'}); onLogout(); } catch (e) { setError(e.message); } };
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="sessions-title"><button className="modal-close" onClick={onClose}><X size={18}/></button><div className="eyebrow">HESAP GÜVENLİĞİ</div><h2 id="sessions-title">Aktif oturumlar</h2><p>Tanımadığın bir oturumu tek tıkla kapatabilirsin.</p><div className="version-list">{sessions.map(item => <div className="version-row" key={item.id}><div><strong>{new Date(item.created_at).toLocaleString('tr-TR')}</strong><span>Son kullanım: {item.last_used_at ? new Date(item.last_used_at).toLocaleString('tr-TR') : 'henüz kullanılmadı'}</span></div><button onClick={() => revoke(item.id)} title="Oturumu kapat"><X size={15}/></button></div>)}{!sessions.length && !error && <p>Aktif oturum bulunmuyor.</p>}</div>{error && <div className="error">{error}</div>}<button className="secondary" onClick={revokeAll}>Tüm oturumları kapat</button></section></div>;
}

export function NewFolderDialog({onClose, onCreate}) {
  const [name, setName] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const submit = async event => { event.preventDefault(); if (!name.trim()) { setError('Klasör adı boş olamaz.'); return; } setBusy(true); setError(''); try { await onCreate(name); } catch (e) { setError(e.message); setBusy(false); } };
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="new-folder-title"><button className="modal-close" onClick={onClose}><X size={18}/></button><div className="eyebrow">KLASÖR OLUŞTUR</div><h2 id="new-folder-title">Yeni klasör</h2><form onSubmit={submit}><label>Klasör adı<input autoFocus required maxLength={255} value={name} onChange={e => setName(e.target.value)} placeholder="Örn. Projeler"/></label>{error && <div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy ? 'Oluşturuluyor…' : 'Klasör oluştur'}</button></form></section></div>;
}

function FileCard({file, selected, onSelect, shared, trashed, onShare, onVersions, onMove, onRename, onDownload, onTrash, onRestore, onDelete}) {
  const [thumbnail, setThumbnail] = useState('');
  useEffect(() => { if (file.content_type?.startsWith('image/') || file.content_type === 'application/pdf') api(`/v1/files/${file.id}/thumbnail`).then(result => setThumbnail(result.url)).catch(() => {}); }, [file.id]);
  return <article className={`file-card${selected ? ' is-selected' : ''}`}>{!trashed && !shared && <input className="file-select" type="checkbox" checked={selected} onChange={onSelect} aria-label={`${file.name} seç`}/>} {thumbnail ? <img src={thumbnail} alt=""/> : <div className="file-icon"><ImageIcon size={24}/></div>}<div className="file-info"><strong title={file.name}>{file.name}</strong><span>{shared ? `Paylaşan: ${file.shared_by}` : `${formatBytes(file.size_bytes)} · ${new Date(file.created_at).toLocaleDateString('tr-TR')}`}</span></div>{trashed ? <TrashActions onRestore={onRestore} onDelete={onDelete}/> : shared ? <div className="card-actions"><button onClick={onDownload} aria-label={`${file.name} indir`} title="İndir"><Download size={16}/></button></div> : <div className="card-actions"><button onClick={onDownload} aria-label={`${file.name} indir`} title="İndir"><Download size={16}/></button><button onClick={onVersions} aria-label={`${file.name} sürümleri`} title="Sürümler"><History size={16}/></button><button onClick={onRename} aria-label={`${file.name} yeniden adlandır`} title="Yeniden adlandır"><Pencil size={16}/></button><button onClick={onShare} aria-label={`${file.name} dosyasını paylaş`} title="Paylaş"><Share2 size={16}/></button><button onClick={onMove} aria-label={`${file.name} dosyasını taşı`} title="Taşı"><FolderInput size={16}/></button><button onClick={onTrash} aria-label={`${file.name} dosyasını çöp kutusuna taşı`} title="Çöp kutusuna taşı"><Trash2 size={16}/></button></div>}</article>;
}

function TrashActions({onRestore, onDelete}) {
  return <div className="card-actions"><button onClick={onRestore} aria-label="Geri yükle" title="Geri yükle"><RotateCcw size={16}/></button><button className="danger" onClick={onDelete} aria-label="Kalıcı sil" title="Kalıcı sil"><Trash2 size={16}/></button></div>;
}

function VersionsDialog({file, onClose, onRestored}) {
  const [versions, setVersions] = useState([]), [error, setError] = useState('');
  useEffect(() => { api(`/v1/files/${file.id}/versions`).then(result => setVersions(result.versions || result)).catch(e => setError(e.message)); }, [file.id]);
  const download = async version => { try { const result = await api(`/v1/files/${file.id}/versions/${version.id}/download`); window.open(result.url, '_blank', 'noopener,noreferrer'); } catch (e) { setError(e.message); } };
  const remove = async version => { if (!window.confirm('Bu eski sürüm kalıcı olarak silinsin mi?')) return; try { await api(`/v1/files/${file.id}/versions/${version.id}`, {method: 'DELETE'}); setVersions(current => current.filter(item => item.id !== version.id)); } catch (e) { setError(e.message); } };
  const restore = async version => { try { await api(`/v1/files/${file.id}/versions/${version.id}/restore`, {method: 'POST'}); onRestored(); } catch (e) { setError(e.message); } };
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="versions-title"><button className="modal-close" onClick={onClose}><X size={18}/></button><div className="eyebrow">DOSYA GEÇMİŞİ</div><h2 id="versions-title">{file.name}</h2>{error && <div className="error">{error}</div>}<div className="version-list">{versions.map(version => <div className="version-row" key={version.id}><div><strong>{version.is_current ? 'Güncel sürüm' : 'Önceki sürüm'}</strong><span>{formatBytes(version.size_bytes)} · {new Date(version.created_at).toLocaleString('tr-TR')}</span></div><div><button onClick={() => download(version)} title="İndir"><Download size={15}/></button>{!version.is_current && <><button onClick={() => restore(version)} title="Bu sürümü geri yükle"><RotateCcw size={15}/></button><button onClick={() => remove(version)} title="Sürümü sil"><Trash2 size={15}/></button></>}</div></div>)}{!versions.length && !error && <p>Henüz sürüm geçmişi bulunmuyor.</p>}</div></section></div>;
}

function ShareDialog({file, onClose}) {
  const [password, setPassword] = useState(''), [url, setURL] = useState(''), [email, setEmail] = useState(''), [permission, setPermission] = useState('read'), [grants, setGrants] = useState([]), [notice, setNotice] = useState(''), [error, setError] = useState('');
  useEffect(() => { api(`/v1/files/${file.id}/access`).then(result => setGrants(result.access || [])).catch(() => {}); }, [file.id]);
  const create = async e => { e.preventDefault(); setError(''); try { const result = await api(`/v1/files/${file.id}/shares`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({password})}); setURL(result.url); } catch (requestError) { setError(requestError.message); } };
  const grant = async e => { e.preventDefault(); setError(''); try { const result = await api(`/v1/files/${file.id}/access`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({email, permission})}); setGrants(current => [...current, result]); setNotice('Dosya kullanıcıya paylaşıldı.'); setEmail(''); } catch (requestError) { setError(requestError.message); } };
  const revoke = async id => { try { await api(`/v1/file-access/${id}`, {method: 'DELETE'}); setGrants(current => current.filter(item => item.id !== id)); } catch (e) { setError(e.message); } };
  const changePermission = async (id, next) => { try { await api(`/v1/file-access/${id}`, {method: 'PATCH', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({permission: next})}); setGrants(current => current.map(item => item.id === id ? {...item, permission: next} : item)); } catch (e) { setError(e.message); } };
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="share-title"><button className="modal-close" onClick={onClose}><X size={18}/></button><div className="eyebrow">GÜVENLİ PAYLAŞIM</div><h2 id="share-title">{file.name}</h2>{grants.length > 0 && <div className="grant-list">{grants.map(item => <div className="grant-row" key={item.id}><span>{item.grantee_email || item.owner_email}</span><select value={item.permission} onChange={e => changePermission(item.id, e.target.value)}><option value="read">Görüntüleme</option><option value="write">Düzenleme</option></select><button onClick={() => revoke(item.id)} title="Erişimi kaldır"><X size={15}/></button></div>)}</div>}<form onSubmit={grant}><label>Kullanıcı e-postası<input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="alıcı@ornek.com"/></label><label>Yetki<select value={permission} onChange={e => setPermission(e.target.value)}><option value="read">Görüntüleme</option><option value="write">Düzenleme</option></select></label><button className="primary">Kullanıcıyla paylaş</button></form><hr/><p>veya public bağlantı oluştur</p>{url ? <div className="copy-row"><input readOnly value={url}/><button className="primary" onClick={() => navigator.clipboard.writeText(url)}>Kopyala</button></div> : <form onSubmit={create}><label>Bağlantı parolası<input value={password} onChange={e => setPassword(e.target.value)} type="password" placeholder="Boş bırakılabilir"/></label><button className="secondary">Bağlantı oluştur</button></form>}{notice && <div className="success">{notice}</div>}{error && <div className="error">{error}</div>}</section></div>;
}

function MoveDialog({file, files, onClose, onMoved}) {
  const items = files || [file];
  const [folders, setFolders] = useState([]), [folderID, setFolderID] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { api('/v1/folders').then(result => setFolders(result.folders || result.items || result)).catch(e => setError(e.message)); }, []);
  const move = async e => { e.preventDefault(); setBusy(true); setError(''); try { const path = items.length === 1 ? `/v1/files/${items[0].id}/move` : '/v1/files/bulk/move'; const body = items.length === 1 ? {folder_id: folderID || null} : {ids: items.map(item => item.id), folder_id: folderID || null}; await api(path, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(body)}); onMoved(); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } };
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="move-title"><button className="modal-close" onClick={onClose}><X size={18}/></button><div className="eyebrow">DOSYAYI TAŞI</div><h2 id="move-title">{items.length === 1 ? items[0].name : `${items.length} dosyayı taşı`}</h2><form onSubmit={move}><label>Hedef klasör<select value={folderID} onChange={e => setFolderID(e.target.value)}><option value="">Kök dizin</option>{folders.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{error && <div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy ? 'Taşınıyor…' : 'Taşı'}</button></form></section></div>;
}

const rootElement = document.getElementById('root');
if (rootElement) createRoot(rootElement).render(<App/>);
